version: '3.8'

services:
  global-redis:
    image: redis:alpine
    container_name: global-redis
    ports:
      - "6379:6379"
    networks:
      - ff-shared-net

networks:
  ff-shared-net:
    name: ff-shared-net
    driver: bridge
